name: Print Date and Time

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  show-date-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Show current date and time
        run: date
